name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
      - name: Install modules
        run: pnpm install
      - name: Run Typecheck
        run: pnpm tsc
      - name: Run Oxlint
        run: pnpm run oxlint
      - run: pnpm run build
